ldapconnection.cpp - fix unused-const-variable
Encountered if LDAP_FOUND is false

Fixes:
```
src/core/ldapconnection.cpp:19:30: error: unused variable 'callbacks'
 [-Werror,-Wunused-const-variable]
   19 | static const sasl_callback_t callbacks[] = {{SASL_CB_ECHOPROMPT, nullptr, nullptr},
```